In [0]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [0]:
test = pd.read_csv("/content/test.csv")
train = pd.read_csv("/content/train.csv")

In [0]:
train.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [0]:
columns = ["Ticket","Cabin"]
test = test.drop(columns=columns)
train = train.drop(columns=columns)

In [0]:
train.head()

PassengerId  Survived  Pclass  ... Parch     Fare  Embarked
0            1         0       3  ...     0   7.2500         S
1            2         1       1  ...     0  71.2833         C
2            3         1       3  ...     0   7.9250         S
3            4         1       1  ...     0  53.1000         S
4            5         0       3  ...     0   8.0500         S

[5 rows x 10 columns]

In [0]:
train.drop(["PassengerId"],axis=1,inplace=True)

In [0]:
train.head()

Survived  Pclass  ...     Fare Embarked
0         0       3  ...   7.2500        S
1         1       1  ...  71.2833        C
2         1       3  ...   7.9250        S
3         1       1  ...  53.1000        S
4         0       3  ...   8.0500        S

[5 rows x 9 columns]

In [0]:

train["Name"][0].split(',')[1].split('.')[0].strip()

'Mr'

In [0]:
def get_titles(data):
  data["Title"] = data["Name"].map(lambda x:x.split(',')[1].split('.')[0].strip())
  return data

In [0]:
train = get_titles(train)

In [0]:
train.head()

Survived  Pclass  ... Embarked Title
0         0       3  ...        S    Mr
1         1       1  ...        C   Mrs
2         1       3  ...        S  Miss
3         1       1  ...        S   Mrs
4         0       3  ...        S    Mr

[5 rows x 10 columns]

In [0]:
test = get_titles(test)

In [0]:
train.drop(["Name"],axis=1,inplace=True)
test.drop(["Name"],axis=1,inplace = True)

In [0]:
train.Title.unique()

array(['Mr', 'Mrs', 'Miss', 'Master', 'Don', 'Rev', 'Dr', 'Mme', 'Ms',
       'Major', 'Lady', 'Sir', 'Mlle', 'Col', 'Capt', 'the Countess',
       'Jonkheer'], dtype=object)

In [0]:
test.Title.unique()

array(['Mr', 'Mrs', 'Miss', 'Master', 'Ms', 'Col', 'Rev', 'Dr', 'Dona'],
      dtype=object)

In [0]:
title_dict = {
    "Capt": "Rare",
    "Col": "Rare",
    "Major": "Rare",
    "Jonkheer": "Rare",
    "Don": "Rare",
    "Dona": "Miss",
    "Sir" : "Rare",
    "Dr": "Rare",
    "Rev": "Rare",
    "the Countess":"Rare",
    "Mme": "Mrs",
    "Mlle": "Miss",
    "Ms": "Mrs",
    "Mr" : "Mr",
    "Mrs" : "Mrs",
    "Miss" : "Miss",
    "Master" : "Master",
    "Lady" : "Rare"
}

In [0]:
train.Title = train.Title.map(title_dict)
test.Title = test.Title.map(title_dict)

In [0]:
train.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked Title
0         0       3    male  22.0      1      0   7.2500        S    Mr
1         1       1  female  38.0      1      0  71.2833        C   Mrs
2         1       3  female  26.0      0      0   7.9250        S  Miss
3         1       1  female  35.0      1      0  53.1000        S   Mrs
4         0       3    male  35.0      0      0   8.0500        S    Mr

In [0]:
train["Embarked"].fillna(train["Embarked"].mode()[0],inplace=True)

In [0]:
train.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      0
Title         0
dtype: int64

In [0]:
test["Embarked"].fillna(test["Embarked"].mode()[0],inplace = True)

In [0]:
test.isnull().sum()

PassengerId     0
Pclass          0
Sex             0
Age            86
SibSp           0
Parch           0
Fare            1
Embarked        0
Title           0
dtype: int64

In [0]:
test["Fare"].fillna(test["Fare"].median(),inplace=True)

In [0]:
grp = test.groupby(["Pclass","Sex"])

In [0]:
grp.median()

PassengerId   Age  SibSp  Parch      Fare
Pclass Sex                                              
1      female       1088.0  41.0    0.0    0.0  79.02500
       male         1094.0  42.0    0.0    0.0  51.86250
2      female       1122.0  24.0    0.0    0.0  26.00000
       male         1122.0  28.0    0.0    0.0  13.00000
3      female       1070.5  22.0    0.0    0.0   8.08125
       male         1102.5  24.0    0.0    0.0   7.89580

In [0]:
grp.median().reset_index()

Pclass     Sex  PassengerId   Age  SibSp  Parch      Fare
0       1  female       1088.0  41.0    0.0    0.0  79.02500
1       1    male       1094.0  42.0    0.0    0.0  51.86250
2       2  female       1122.0  24.0    0.0    0.0  26.00000
3       2    male       1122.0  28.0    0.0    0.0  13.00000
4       3  female       1070.5  22.0    0.0    0.0   8.08125
5       3    male       1102.5  24.0    0.0    0.0   7.89580

In [0]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
me = LabelEncoder()
train["Sex"] = le.fit_transform(train["Sex"])
test["Sex"] = me.fit_transform(test["Sex"])

In [0]:
train.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked Title
0         0       3    1  22.0      1      0   7.2500        S    Mr
1         1       1    0  38.0      1      0  71.2833        C   Mrs
2         1       3    0  26.0      0      0   7.9250        S  Miss
3         1       1    0  35.0      1      0  53.1000        S   Mrs
4         0       3    1  35.0      0      0   8.0500        S    Mr

In [0]:
test.head()

PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare Embarked Title
0          892       3    1  34.5      0      0   7.8292        Q    Mr
1          893       3    0  47.0      1      0   7.0000        S   Mrs
2          894       2    1  62.0      0      0   9.6875        Q    Mr
3          895       3    1  27.0      0      0   8.6625        S    Mr
4          896       3    0  22.0      1      1  12.2875        S   Mrs

In [0]:
grouped_median_train = train.groupby(['Sex','Pclass','Title']).median()
grouped_median_train = grouped_median_train.reset_index()[['Sex', 'Pclass', 'Title', 'Age']]
def fill_age(row):
    condition = (
        (grouped_median_train['Sex'] == row['Sex']) & 
        (grouped_median_train['Title'] == row['Title']) & 
        (grouped_median_train['Pclass'] == row['Pclass'])
    ) 
    if np.isnan(grouped_median_train[condition]['Age'].values[0]):
        print('true')
        condition = (
            (grouped_median_train['Sex'] == row['Sex']) & 
            (grouped_median_train['Pclass'] == row['Pclass'])
        )

    return grouped_median_train[condition]['Age'].values[0]


def process_age(data):
    
    data.Age = data.apply(lambda row: fill_age(row) if np.isnan(row['Age']) else row['Age'], axis=1)
    return data

train = process_age(train)
test = process_age(test) 



In [0]:
train.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
Title       0
dtype: int64

In [0]:
test.isnull().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
Title          0
dtype: int64

In [0]:
def process_family(data):
    data['FamilySize'] = data['Parch'] + data['SibSp'] + 1 
    return data
train = process_family(train)
test = process_family(test)

In [0]:
train = train.drop(['SibSp'], axis = 1)
test  = test.drop(['SibSp'], axis = 1)

In [0]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
Survived      891 non-null int64
Pclass        891 non-null int64
Sex           891 non-null int64
Age           891 non-null float64
Parch         891 non-null int64
Fare          891 non-null float64
Embarked      891 non-null object
Title         891 non-null object
FamilySize    891 non-null int64
dtypes: float64(2), int64(5), object(2)
memory usage: 62.8+ KB


In [0]:
embarked_map = {
    'Q' : 0,
    'S' : 1,
    'C' : 2
}

title_map = {
             "Mr": 1, 
             "Master": 2, 
             "Mrs": 3, 
             "Miss": 4, 
             "Rare": 5
            }

In [0]:
train.Embarked = train.Embarked.map(embarked_map)
test.Embarked = test.Embarked.map(embarked_map)
train.Title = train.Title.map(title_map)
test.Title = test.Title.map(title_map)

In [0]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
Survived      891 non-null int64
Pclass        891 non-null int64
Sex           891 non-null int64
Age           891 non-null float64
Parch         891 non-null int64
Fare          891 non-null float64
Embarked      891 non-null int64
Title         891 non-null int64
FamilySize    891 non-null int64
dtypes: float64(2), int64(7)
memory usage: 62.8 KB


In [0]:
y = train["Survived"]
train = train.drop(columns = ["Survived"])
X = train
train.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
Pclass        891 non-null int64
Sex           891 non-null int64
Age           891 non-null float64
Parch         891 non-null int64
Fare          891 non-null float64
Embarked      891 non-null int64
Title         891 non-null int64
FamilySize    891 non-null int64
dtypes: float64(2), int64(6)
memory usage: 55.8 KB


In [0]:
y.to_csv("/content/y.csv",index=False)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  """Entry point for launching an IPython kernel.


In [0]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
Pclass        891 non-null int64
Sex           891 non-null int64
Age           891 non-null float64
Parch         891 non-null int64
Fare          891 non-null float64
Embarked      891 non-null int64
Title         891 non-null int64
FamilySize    891 non-null int64
dtypes: float64(2), int64(6)
memory usage: 55.8 KB


In [0]:
test.head()

PassengerId  Pclass  Sex   Age  Parch     Fare  Embarked  Title  FamilySize
0          892       3    1  34.5      0   7.8292         0      1           1
1          893       3    0  47.0      0   7.0000         1      3           2
2          894       2    1  62.0      0   9.6875         0      1           1
3          895       3    1  27.0      0   8.6625         1      1           1
4          896       3    0  22.0      1  12.2875         1      3           3

In [0]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Sex            418 non-null int64
Age            418 non-null float64
Parch          418 non-null int64
Fare           418 non-null float64
Embarked       418 non-null int64
Title          418 non-null int64
FamilySize     418 non-null int64
dtypes: float64(2), int64(7)
memory usage: 29.5 KB


In [0]:
train.to_csv("/content/train_mod.csv", index=False)

In [0]:
test.to_csv("/content/test_mod.csv",index = False)

In [0]:
from sklearn.model_selection import StratifiedKFold,cross_val_score,GridSearchCV
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
param_grid = { 
    'n_estimators': [200, 500],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth' : [4,5,6,7,8],
    'criterion' :['gini', 'entropy']
}
kf = StratifiedKFold(n_splits=5)
grfc = GridSearchCV(estimator = rfc,param_grid=param_grid,cv=10)


In [0]:
grfc.fit(X,y)

GridSearchCV(cv=10, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False,
                                              rand

In [0]:
grfc.best_score_

0.8395255930087391

In [0]:
rfc1 = RandomForestClassifier(n_estimators=500,max_depth=7,criterion='gini',max_features='log2')

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_tes,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=101)

In [0]:
rfc1.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=7, max_features='log2',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [0]:
y_pred = rfc1.predict(X_tes)

In [0]:
score = cross_val_score(rfc1,X,y,scoring = 'accuracy',cv=kf)

In [0]:
score


array([0.84357542, 0.82022472, 0.84831461, 0.81460674, 0.8258427 ])

In [0]:
y_pred = rfc1.predict(X_tes)

In [0]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test,y_pred)

In [0]:
acc

0.8324022346368715

In [0]:
X_test = test
X_test = X_test.drop(columns=["PassengerId"])

In [0]:
y_pred = rfc1.predict(X_test)

In [0]:
y_pred

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [0]:
rfc_grid = pd.DataFrame({
        "PassengerId": test["PassengerId"],
        "Survived": y_pred
    })

In [0]:
rfc_grid.to_csv("/content/rfc_grid_data10.csv", index=False)

In [0]:
from sklearn.ensemble import AdaBoostClassifier
n_estimators = [100,140,145,150,160, 170,175,180,185];
learning_r = [0.1,1,0.01,0.5]

parameters = {'n_estimators':n_estimators,
              'learning_rate':learning_r
              
        }
grid = GridSearchCV(AdaBoostClassifier(base_estimator= None, 
                                     ),
                                 param_grid=parameters,
                                 cv=10,
                                 n_jobs = -1)
grid.fit(X,y) 

GridSearchCV(cv=10, error_score=nan,
             estimator=AdaBoostClassifier(algorithm='SAMME.R',
                                          base_estimator=None,
                                          learning_rate=1.0, n_estimators=50,
                                          random_state=None),
             iid='deprecated', n_jobs=-1,
             param_grid={'learning_rate': [0.1, 1, 0.01, 0.5],
                         'n_estimators': [100, 140, 145, 150, 160, 170, 175,
                                          180, 185]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [0]:
grid.best_score_

0.823820224719101

In [0]:
ar = AdaBoostClassifier(learning_rate=1,n_estimators=150)
ar.fit(X_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1,
                   n_estimators=150, random_state=None)

In [0]:
accuracy_score(y_test,ar.predict(X_tes))

0.8324022346368715

In [0]:
score = cross_val_score(ar,X,y,scoring = 'accuracy',cv=kf)

In [0]:
score

array([0.81005587, 0.80898876, 0.83146067, 0.81460674, 0.8258427 ])

In [0]:
y_pred1 = ar.predict(X_test)
rfc_grid = pd.DataFrame({
        "PassengerId": test["PassengerId"],
        "Survived": y_pred1
    })
rfc_grid.to_csv("/content/ada_grid_data2.csv", index=False)

In [0]:
from sklearn.ensemble import GradientBoostingClassifier

gbk = GradientBoostingClassifier()
gbk.fit(X_train, y_train)
y_pred = gbk.predict(X_tes)
acc_gbk = round(accuracy_score(y_pred, y_test) * 100, 2)
print(acc_gbk)

84.92


In [0]:
xgb_params = {
        'n_estimators': [200, 500],
        'subsample': [0.6, 1.0],
        'max_depth': [2,5,8],
        'learning_rate': [0.1,0.01,0.02],
        "min_samples_split": [2,5,10]}

In [0]:
xgb = GradientBoostingClassifier()

xgb_cv_model = GridSearchCV(xgb, xgb_params, cv = 10, n_jobs = -1, verbose = 2)
xgb_cv_model.fit(X_train, y_train)

Fitting 10 folds for each of 108 candidates, totalling 1080 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  37 tasks      | elapsed:    9.2s
[Parallel(n_jobs=-1)]: Done 158 tasks      | elapsed:   44.5s
[Parallel(n_jobs=-1)]: Done 361 tasks      | elapsed:  2.7min
[Parallel(n_jobs=-1)]: Done 644 tasks      | elapsed:  4.7min
[Parallel(n_jobs=-1)]: Done 1009 tasks      | elapsed:  7.5min
[Parallel(n_jobs=-1)]: Done 1080 out of 1080 | elapsed:  8.4min finished


GridSearchCV(cv=10, error_score=nan,
             estimator=GradientBoostingClassifier(ccp_alpha=0.0,
                                                  criterion='friedman_mse',
                                                  init=None, learning_rate=0.1,
                                                  loss='deviance', max_depth=3,
                                                  max_features=None,
                                                  max_leaf_nodes=None,
                                                  min_impurity_decrease=0.0,
                                                  min_impurity_split=None,
                                                  min_samples_leaf=1,
                                                  min_samples_split=2,
                                                  min_weight_fraction_leaf=0.0,
                                                  n_estimators=100,
                                                  n_iter_no_...
                 

In [0]:
xgb_cv_model.best_params_

{'learning_rate': 0.1,
 'max_depth': 2,
 'min_samples_split': 10,
 'n_estimators': 200,
 'subsample': 0.6}

In [0]:
xgb = GradientBoostingClassifier(learning_rate = xgb_cv_model.best_params_["learning_rate"], 
                    max_depth = xgb_cv_model.best_params_["max_depth"],
                    min_samples_split = xgb_cv_model.best_params_["min_samples_split"],
                    n_estimators = xgb_cv_model.best_params_["n_estimators"],
                    subsample = xgb_cv_model.best_params_["subsample"])


In [0]:
xgb_tuned =  xgb.fit(X_train,y_train)

In [0]:
y_pred = xgb_tuned.predict(X_tes)
acc_gbk = round(accuracy_score(y_pred, y_test) * 100, 2)
print(acc_gbk)

82.68


In [0]:
score = cross_val_score(xgb_tuned,X,y,scoring='accuracy',cv=kf)

In [0]:
score

array([0.83798883, 0.82022472, 0.84269663, 0.81460674, 0.84831461])

In [0]:
y_pred2 = xgb_tuned.predict(X_test)

In [0]:
rfc_grid = pd.DataFrame({
        "PassengerId": test["PassengerId"],
        "Survived": y_pred2
    })
rfc_grid.to_csv("/content/gc_grid_data2.csv", index=False)

In [0]:
grfc.best_params_

{'criterion': 'gini',
 'max_depth': 8,
 'max_features': 'log2',
 'n_estimators': 800}

In [0]:
rfc2 = RandomForestClassifier(n_estimators=800,criterion='gini',max_depth=8,max_features='log2',random_state=69)
rfc2.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=8, max_features='log2',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=800,
                       n_jobs=None, oob_score=False, random_state=69, verbose=0,
                       warm_start=False)

In [0]:
accuracy_score(y_test,rfc2.predict(X_tes))

0.8603351955307262

In [0]:
score=cross_val_score(rfc2,X,y,scoring='accuracy',cv=kf)

In [0]:
score

array([0.84357542, 0.81460674, 0.85955056, 0.82022472, 0.83146067])

In [0]:
y_pred3 = rfc2.predict(X_test)
rfc_grid = pd.DataFrame({
        "PassengerId": test["PassengerId"],
        "Survived": y_pred3
    })
rfc_grid.to_csv("/content/rfc_grid_data6.csv", index=False)